### ISSUE TITLE
How do I close a connection?

### ISSUE THREAD

**Issue by najamelan** [jeikabu/runng#26]
I see that structs like `protocol::pair1::Pair1` have methods like `dial` and `listen`, but not `close`?

I wondered about this after running into [this problem](https://github.com/nanomsg/nanomsg/issues/427).  Messages get dropped because the sender shuts down before they have finished sending. I wasn't using threads, but when [sleeping 500ms](https://github.com/najamelan/runng_test/blob/3c1e92973b0e131cb979ec70bfeaf3212d5a8a7a/src/peerb.rs#L20) before shutting the program down I can't reproduce the problem anymore, so I suppose it's what happens.

I wondered if a `close` method could flush the connection and then disconnect? And if that could prevent problems like this.

**Comment by jeikabu** [comment]
NngSocket has a `Arc<InnerSocket>` with `impl Drop`. I should document that somewhere. 
Thanks for these suggestions, it's very helpful to get a second opinion.

**Comment by najamelan** [comment]
Ok, so I can do `pair1.socket()` to obtain `NngSocket`, but then how do I make it drop?

You're most welcome for the feedback. Thanks for writing this. IPC isn't trivial right now in rust. And yeah, zeromq seems to be a bit dated.
