### ISSUE TITLE
Question on runng vs nng-rs

### ISSUE THREAD

**Issue by janjaapbos** [jeikabu/runng#66]
I have been looking at nng-rs and runng. What are the main differences?

Am I correct to state:
- nng-rs is a rust safe implementation that follows closely the nng-sys / nng API
- runng adds further logic, including async patterns, to best support Aio in NNG in Rust?

**Comment by jeikabu** [comment]
That's the gist of it.

**Comment by janjaapbos** [comment]
thanks
