### ISSUE TITLE
stream ReadAsync / WriteAsync

### ISSUE THREAD

**Issue by janjaapbos** [jeikabu/runng#68]
I would like to use runng stream as a transport for Remoc (https://crates.io/crates/remoc). Remoc supports two kind of interfaces, Sink/Stream or AsyncRead/AsyncWrite. See https://docs.rs/remoc/0.9.7/remoc/struct.Connect.html.

Would it be possible to support one of these with runng stream?

**Comment by jeikabu** [comment]
I'd think it's possible; Rust's async MVP left a lot undefined/incomplete and I decided to let some things simmer.  That said, the generic `steam` interface isn't completely fleshed out.  I didn't contemplate what additional safety features/boilerplate-reduction/scaffolding I wanted in addition to what's in nng/nng-rs.

**Comment by janjaapbos** [comment]
Thanks for the feedback.
